name: Run Gradle Build on PRs
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4.2

    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
      
    - name: Execute Gradle Build Release
      run: ./gradlew clean build assembleRelease --parallel -x lint

    - name: Upload
      if: github.ref_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: Build Artifacts (${{ matrix.os }})
        path: app/build/outputs/apk/release/
